name: Build and Deploy

env:
  APP_NAME: valkyr

on:
  push:
    branches: main

jobs:
  build:
    name: Build Docker image artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $APP_NAME:latest
          docker save $APP_NAME:latest | gzip > image.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            image.tar.gz
            cd/deploy.sh
          retention-days: 1

  deploy:
    name: Deploys Docker image to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy Docker image
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > ./key
          chmod 0600 ./key
          scp -o StrictHostKeyChecking=no -i ./key \
            image.tar.gz $SSH_HOST:images/$APP_NAME.tar.gz
          ssh -o StrictHostKeyChecking=no -i ./key $SSH_HOST \
            'bash -s' < cd/deploy.sh
