name: Build and Deploy

env:
  APP_NAME: valkyr

on:
  push:
    branch:
      - main

jobs:
  build:
    name: Build Docker image artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: get_date
        run: |
          echo "build_date=$(date +'%Y/%m/%d')" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --build-arg build_date=${{ steps.get_date.outputs.build_date }} \
            --tag $APP_NAME:latest
          docker save $APP_NAME:latest | gzip > image.tar.gz
      - name: Deploy Docker image
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > ./key
          chmod 0600 ./key
          scp -o StrictHostKeyChecking=no -i ./key \
            image.tar.gz $SSH_HOST:images/$APP_NAME.tar.gz
          ssh -o StrictHostKeyChecking=no -i ./key $SSH_HOST \
            'bash -s' < ci/deploy.sh
